### PR TITLE
fix(backend): compatibility issues

### PR DESCRIPTION
**Pull request by kakkokari-gtyih**
## Additional info (optional)

suqash

そのうちリバート

## Checklist
- [ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

**Review by kanarikanaru — APPROVED** [review]

**Comment by kanarikanaru** [comment]
e2eみてマージする

**Comment by kakkokari-gtyih** [comment]
たぶんこれで通ると思う

**Comment by kanarikanaru** [comment]
触ってないはずのところなのでもう一回回す

**Comment by kanarikanaru** [comment]
🙏 🙏

**Pull request merged**
